/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.practica5joaquinzavala.vista;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        cantanteMenu = new javax.swing.JMenu();
        crearCantanteMenuItem = new javax.swing.JMenuItem();
        eliminarCantanteMenuItem = new javax.swing.JMenuItem();
        actualizarCantanteMenuItem = new javax.swing.JMenuItem();
        listarCantanteMenuItem = new javax.swing.JMenuItem();
        BuscarCantanteMenuItem = new javax.swing.JMenuItem();
        compositorMenu = new javax.swing.JMenu();
        crearCompositorMenuItem = new javax.swing.JMenuItem();
        eliminarCompositorMenuItem = new javax.swing.JMenuItem();
        actualizarComposiorMenuItem = new javax.swing.JMenuItem();
        listarCompositorMenuItem = new javax.swing.JMenuItem();
        BuscarCompositorMenuItem = new javax.swing.JMenuItem();
        discoMenu = new javax.swing.JMenu();
        crearDiscoMenuItem = new javax.swing.JMenuItem();
        eliminarDiscoMenuItem = new javax.swing.JMenuItem();
        actualizarDiscoMenuItem = new javax.swing.JMenuItem();
        listarDiscoMenuItem = new javax.swing.JMenuItem();
        BuscarDiscoMenuItem1 = new javax.swing.JMenuItem();
        cancionMenu = new javax.swing.JMenu();
        crearCancionMenuItem = new javax.swing.JMenuItem();
        eliminarCancionMenuItem = new javax.swing.JMenuItem();
        actualizarCancionMenuItem = new javax.swing.JMenuItem();
        listarCancionMenuItem = new javax.swing.JMenuItem();
        BuscarCancionMenuItem = new javax.swing.JMenuItem();
        opcionesMenu = new javax.swing.JMenu();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cantanteMenu.setMnemonic('f');
        cantanteMenu.setText("Cantante");

        crearCantanteMenuItem.setMnemonic('o');
        crearCantanteMenuItem.setText("Crear");
        crearCantanteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCantanteMenuItemActionPerformed(evt);
            }
        });
        cantanteMenu.add(crearCantanteMenuItem);

        eliminarCantanteMenuItem.setMnemonic('s');
        eliminarCantanteMenuItem.setText("Eliminar");
        cantanteMenu.add(eliminarCantanteMenuItem);

        actualizarCantanteMenuItem.setMnemonic('a');
        actualizarCantanteMenuItem.setText("Actualizar");
        cantanteMenu.add(actualizarCantanteMenuItem);

        listarCantanteMenuItem.setMnemonic('x');
        listarCantanteMenuItem.setText("Listar");
        listarCantanteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCantanteMenuItemActionPerformed(evt);
            }
        });
        cantanteMenu.add(listarCantanteMenuItem);

        BuscarCantanteMenuItem.setText("Buscar");
        BuscarCantanteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCantanteMenuItemActionPerformed(evt);
            }
        });
        cantanteMenu.add(BuscarCantanteMenuItem);

        menuBar.add(cantanteMenu);

        compositorMenu.setMnemonic('e');
        compositorMenu.setText("Compositor");

        crearCompositorMenuItem.setMnemonic('o');
        crearCompositorMenuItem.setText("Crear");
        crearCompositorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCompositorMenuItemActionPerformed(evt);
            }
        });
        compositorMenu.add(crearCompositorMenuItem);

        eliminarCompositorMenuItem.setMnemonic('s');
        eliminarCompositorMenuItem.setText("Eliminar");
        compositorMenu.add(eliminarCompositorMenuItem);

        actualizarComposiorMenuItem.setMnemonic('a');
        actualizarComposiorMenuItem.setText("Actualizar");
        compositorMenu.add(actualizarComposiorMenuItem);

        listarCompositorMenuItem.setMnemonic('x');
        listarCompositorMenuItem.setText("Listar");
        listarCompositorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCompositorMenuItemActionPerformed(evt);
            }
        });
        compositorMenu.add(listarCompositorMenuItem);

        BuscarCompositorMenuItem.setText("Buscar");
        BuscarCompositorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCompositorMenuItemActionPerformed(evt);
            }
        });
        compositorMenu.add(BuscarCompositorMenuItem);

        menuBar.add(compositorMenu);

        discoMenu.setMnemonic('h');
        discoMenu.setText("Disco");

        crearDiscoMenuItem.setMnemonic('o');
        crearDiscoMenuItem.setText("Crear");
        crearDiscoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDiscoMenuItemActionPerformed(evt);
            }
        });
        discoMenu.add(crearDiscoMenuItem);

        eliminarDiscoMenuItem.setMnemonic('s');
        eliminarDiscoMenuItem.setText("Eliminar");
        discoMenu.add(eliminarDiscoMenuItem);

        actualizarDiscoMenuItem.setMnemonic('a');
        actualizarDiscoMenuItem.setText("Actualizar");
        discoMenu.add(actualizarDiscoMenuItem);

        listarDiscoMenuItem.setMnemonic('x');
        listarDiscoMenuItem.setText("Listar");
        listarDiscoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarDiscoMenuItemActionPerformed(evt);
            }
        });
        discoMenu.add(listarDiscoMenuItem);

        BuscarDiscoMenuItem1.setText("Buscar");
        BuscarDiscoMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDiscoMenuItem1ActionPerformed(evt);
            }
        });
        discoMenu.add(BuscarDiscoMenuItem1);

        menuBar.add(discoMenu);

        cancionMenu.setText("Cancion");

        crearCancionMenuItem.setMnemonic('o');
        crearCancionMenuItem.setText("Crear");
        crearCancionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCancionMenuItemActionPerformed(evt);
            }
        });
        cancionMenu.add(crearCancionMenuItem);

        eliminarCancionMenuItem.setMnemonic('s');
        eliminarCancionMenuItem.setText("Eliminar");
        cancionMenu.add(eliminarCancionMenuItem);

        actualizarCancionMenuItem.setMnemonic('a');
        actualizarCancionMenuItem.setText("Actualizar");
        cancionMenu.add(actualizarCancionMenuItem);

        listarCancionMenuItem.setMnemonic('x');
        listarCancionMenuItem.setText("Listar");
        listarCancionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCancionMenuItemActionPerformed(evt);
            }
        });
        cancionMenu.add(listarCancionMenuItem);

        BuscarCancionMenuItem.setText("Buscar");
        BuscarCancionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCancionMenuItemActionPerformed(evt);
            }
        });
        cancionMenu.add(BuscarCancionMenuItem);

        menuBar.add(cancionMenu);

        opcionesMenu.setText("Opciones");

        salirMenuItem.setText("Salir");
        opcionesMenu.add(salirMenuItem);

        menuBar.add(opcionesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarCantanteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCantanteMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_listarCantanteMenuItemActionPerformed

    private void crearCantanteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCantanteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCantanteMenuItemActionPerformed

    private void listarCompositorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCompositorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarCompositorMenuItemActionPerformed

    private void crearCompositorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCompositorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCompositorMenuItemActionPerformed

    private void crearDiscoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDiscoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearDiscoMenuItemActionPerformed

    private void listarDiscoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDiscoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarDiscoMenuItemActionPerformed

    private void crearCancionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCancionMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCancionMenuItemActionPerformed

    private void listarCancionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCancionMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarCancionMenuItemActionPerformed

    private void BuscarCantanteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCantanteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCantanteMenuItemActionPerformed

    private void BuscarCompositorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCompositorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCompositorMenuItemActionPerformed

    private void BuscarDiscoMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDiscoMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDiscoMenuItem1ActionPerformed

    private void BuscarCancionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCancionMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCancionMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscarCancionMenuItem;
    private javax.swing.JMenuItem BuscarCantanteMenuItem;
    private javax.swing.JMenuItem BuscarCompositorMenuItem;
    private javax.swing.JMenuItem BuscarDiscoMenuItem1;
    private javax.swing.JMenuItem actualizarCancionMenuItem;
    private javax.swing.JMenuItem actualizarCantanteMenuItem;
    private javax.swing.JMenuItem actualizarComposiorMenuItem;
    private javax.swing.JMenuItem actualizarDiscoMenuItem;
    private javax.swing.JMenu cancionMenu;
    private javax.swing.JMenu cantanteMenu;
    private javax.swing.JMenu compositorMenu;
    private javax.swing.JMenuItem crearCancionMenuItem;
    private javax.swing.JMenuItem crearCantanteMenuItem;
    private javax.swing.JMenuItem crearCompositorMenuItem;
    private javax.swing.JMenuItem crearDiscoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu discoMenu;
    private javax.swing.JMenuItem eliminarCancionMenuItem;
    private javax.swing.JMenuItem eliminarCantanteMenuItem;
    private javax.swing.JMenuItem eliminarCompositorMenuItem;
    private javax.swing.JMenuItem eliminarDiscoMenuItem;
    private javax.swing.JMenuItem listarCancionMenuItem;
    private javax.swing.JMenuItem listarCantanteMenuItem;
    private javax.swing.JMenuItem listarCompositorMenuItem;
    private javax.swing.JMenuItem listarDiscoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu opcionesMenu;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables

}
